import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbars from "@/components/Navbar";
import AdminPage from "./(main)/admin/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <main>{children}</main> */}
        <div className="min-h-screen w-full bg-white relative">
  {/* Dual Gradient Overlay Background */}
          <div
            className="absolute inset-0 z-0"
            style={{
              backgroundImage: `
                linear-gradient(to right, rgba(229,231,235,0.8) 1px, transparent 1px),
                linear-gradient(to bottom, rgba(229,231,235,0.8) 1px, transparent 1px),
                radial-gradient(circle 500px at 20% 80%, rgba(139,92,246,0.3), transparent),
                radial-gradient(circle 500px at 80% 20%, rgba(59,130,246,0.3), transparent)
              `,
              backgroundSize: "48px 48px, 48px 48px, 100% 100%, 100% 100%",
            }}
          />
              <Navbars>
                {/* You can put any children here, or leave it empty if Navbar doesn't need children */}
              </Navbars>
              <AdminPage />

        </div>
      </body>
    </html>
  );
}
